{{- if .Values.ingress.enabled -}}
{{- $fullName := include "fullname" . }}
{{- $httpPort := .Values.service.internalPort }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}  
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ $fullName }}
            servicePort: {{ $httpPort }}
  {{- end -}}            
  {{- if .Values.ingress.tls }}        
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}